required = ["github.com/benbjohnson/tmpl","github.com/golang/protobuf/protoc-gen-go"]

[[dependencies]]
  name = "github.com/Azure/azure-sdk-for-go"
  revision = "bd73d950fa4440dae889bd9917bff7cef539f86e"

[[dependencies]]
  name = "github.com/Azure/go-autorest"
  revision = "8a25372bbfec739b8719a9e3987400d15ef9e179"

[[dependencies]]
  branch = "master"
  name = "github.com/davecgh/go-spew"

[[dependencies]]
  name = "github.com/eclipse/paho.mqtt.golang"
  version = "~1.0.0"

[[dependencies]]
  branch = "master"
  name = "github.com/evanphx/json-patch"

[[dependencies]]
  branch = "master"
  name = "github.com/ghodss/yaml"

[[dependencies]]
  branch = "master"
  name = "github.com/google/uuid"

[[dependencies]]
  name = "github.com/influxdata/influxdb"
  version = "~1.1.0"

[[dependencies]]
  branch = "master"
  name = "github.com/mitchellh/mapstructure"

[[dependencies]]
  branch = "logger-targetmanager-wait"
  name = "github.com/prometheus/prometheus"
  source = "github.com/goller/prometheus"

[[dependencies]]
  branch = "master"
  name = "github.com/shurcooL/markdownfmt"

[[overrides]]
  name = "github.com/Azure/azure-sdk-for-go"
  revision = "bd73d950fa4440dae889bd9917bff7cef539f86e"

[[overrides]]
  name = "github.com/Azure/go-autorest"
  revision = "8a25372bbfec739b8719a9e3987400d15ef9e179"

